apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Values.db.MYSQL_HOST  }}"
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.db.MYSQL_DATABASE }}"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.db.MYSQL_USER }}"
            - name: WORDPRESS_DB_PASSWORD
              value: "{{ .Values.db.MYSQL_PASSWORD }}"
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: app-data

