apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name  }}
  namespace: {{ .Values.db.namespace  }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.app  }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.app  }}
    spec: 
      containers:
        - name: {{ .Values.db.name  }}
          image: {{ .Values.db.image  }}
          ports:
            - containerPort: {{ .Values.db.port  }}
          env:
          - name: MYSQL_HOST
            value: "{{ .Values.db.MYSQL_HOST }}"
          - name: WORDPRESS_DB_PORT
            value: "{{ .Values.db.port }}"
          - name: MYSQL_ROOT_PASSWORD
            value: "{{ .Values.db.MYSQL_ROOT_PASSWORD }}"
          - name: MYSQL_DATABASE
            value: "{{ .Values.db.MYSQL_DATABASE }}"
          - name: MYSQL_USER
            value: "{{ .Values.db.MYSQL_USER }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.db.MYSQL_PASSWORD }}"
          volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-database-pvc
