apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: mysql-database
  storageClassName: ""  # <== This is important to match the manually created PV

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: app-data
  storageClassName: ""  # <== Important

